# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   test:
      name: Run Unit Tests
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v2
        - name: set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8

        - name: Unit tests
          run: |
              sudo chmod +x ./gradlew
              ./gradlew testDevUnitTest --stacktrace

   apk:
       name: Generate APK
       runs-on: ubuntu-latest

       steps:
         - uses: actions/checkout@v2
         - name: set up JDK 1.8
           uses: actions/setup-java@v1
           with:
             java-version: 1.8

         - name: Build dev APK
           run: |
              sudo chmod +x ./gradlew
              ./gradlew assembleDev --stacktrace

         - uses: r0adkll/sign-android-release@v1
           with:
             releaseDirectory: app/build/outputs/apk/dev
             signingKeyBase64: ${{ secrets.DEBUG_KEYSTORE }}
             alias: ${{ secrets.DEBUG_KEYSTORE_ALIAS }}
             keyStorePassword: ${{ secrets.DEBUG_KEYSTORE_PASSWORD }}
             keyPassword: ${{ secrets.DEBUG_KEYSTORE_PASSWORD }}

         - name: Upload APK
           uses: actions/upload-artifact@v2
           with:
             name: app
             path: ${{ steps.sign-app.outputs.signedReleaseFile }}